# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_trext',
            new_name='post_text',
        ),
    ]
